## Numpy indexing and slicing

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[6]

np.int64(7)

In [4]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [5]:
arr[:5]

array([1, 2, 3, 4, 5])

In [6]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [7]:
arr[2::2]

array([3, 5, 7, 9])

## Numpy indexing and slicing of matrix

In [8]:
arr = np.arange(1,31).reshape(6,5)

In [9]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0]

array([1, 2, 3, 4, 5])

In [11]:
arr[0][0]

np.int64(1)

In [12]:
arr[4][3]

np.int64(24)

In [14]:
arr[-1][1]

np.int64(27)

In [15]:
arr[0,4]

np.int64(5)

In [16]:
arr[5,4]

np.int64(30)

In [17]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [18]:
arr[3:6,4:6]

array([[20],
       [25],
       [30]])

In [19]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

## Boolean Indexing

In [20]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
bool_index = arr % 2 == 0

In [22]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])