In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
names = np.array(["vivek","sumit","deepanshu"])
print(names)

['vivek' 'sumit' 'deepanshu']


In [4]:
nums = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
matrix = np.array(nums)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [11]:
np.random.random(5)*10


array([8.10513369, 2.68736696, 0.93800753, 3.93658487, 9.58701537])

In [12]:
np.random.randn(10)

array([ 0.18817159,  1.37787169,  0.53969659,  0.28965216, -0.78462973,
       -0.58937042, -0.98852677,  0.88553832,  0.04495684, -0.16809896])

In [13]:
np.random.randint(6)

5

In [15]:
np.random.randint(1,10)

2

In [16]:
np.random.randint(1,10,5)

array([7, 6, 8, 4, 6], dtype=int32)

## Array Attributes

In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

## Array Attributes

In [21]:
arr.min()

np.int64(1)

In [22]:
arr.max()

np.int64(9)

In [23]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [26]:
arr.mean()

np.float64(5.0)

In [27]:
arr.std()

np.float64(2.581988897471611)

In [28]:
arr.argmax()

np.int64(8)

In [29]:
arr.argmin()

np.int64(0)

## Reshaping and Resizing

In [31]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])