In [1]:
import numpy as np

## Airthmetic operations

In [3]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [4]:
a1+a2

array([ 6,  8, 10, 12])

In [5]:
a1-a2

array([-4, -4, -4, -4])

In [6]:
a1*a2

array([ 5, 12, 21, 32])

In [7]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [8]:
a1//a2

array([0, 0, 0, 0])

In [9]:
a1**a2

array([    1,    64,  2187, 65536])

## Broadcasting

In [11]:
l = [10,20,30,40]
arr = np.array(l)

In [12]:
arr + 10

array([20, 30, 40, 50])

In [13]:
m = np.arange(1,31).reshape(5,6)

In [14]:
m+10

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40]])

## Deep and Shallow Copy 

In [15]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
s = a[0:6]

In [17]:
s

array([1, 2, 3, 4, 5, 6])

In [18]:
s = s*10
s

array([10, 20, 30, 40, 50, 60])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
m1 = np.arange(1,10).reshape(3,3)

In [24]:
m2 = np.arange(11,20).reshape(3,3)

In [25]:
m1 * m2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [26]:
m1 @ m2

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [27]:
np.dot(m1,m2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [28]:
np.transpose(m1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Array Manipulation

In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

 

In [30]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Spiliting Array

In [34]:
c = np.arange(16).reshape(4,4)

In [35]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [37]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [38]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]