In [1]:
import numpy as np

### Valid Sudoku

In [4]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],
    
    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [6]:
sm  = np.sum(s,axis=1)

In [12]:
sm == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [15]:
for num in sm:
    if num != 45:
        print("Soduku is not valid")
        break
else:
    print("Soduku is valid for rows") 

Soduku is valid for rows


In [23]:
a = np.sum(s,axis=0)
a

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [24]:
for num in a:
    if num != 45:
        print("Soduku is not valid")
        break
else:
    print("Soduku is valid for colums")

Soduku is valid for colums


In [30]:
for i in range(0,9,3):
    for j in range(0,9,3):
       mat =  s[i:i+3,j:j+3]
       if np.sum(mat) != 45:
           print("Sudoku is not valid")
           break
else:
    print("Sudoku is Valid ")       

Sudoku is Valid 


## General Question

In [34]:
# Columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18,85,78],   # Student 1
    [19,92,88],   # Student 2
    [17,76,95],   # Student 3
    [18,65,70],   # Student 4
    [20,90,85]    # Student 5
])

In [35]:
data.shape

(5, 3)

In [41]:
st = data[0:,0]
st

array([18, 19, 17, 18, 20])

In [42]:
np.average(st)

np.float64(18.4)

In [43]:
np.mean(data[0:,0])

np.float64(18.4)

In [44]:
m = data[0:,1]

In [45]:
m

array([85, 92, 76, 65, 90])

In [46]:
np.max(data[0:,2])

np.int64(95)

In [49]:
d = data[:,1] > 90
d

array([False,  True, False, False, False])

In [50]:
count = 0
for i in d:
    if i:
        count+=1
print(count)

1


In [51]:
data[data[:,1]>90]

array([[19, 92, 88]])

In [54]:
data[:,1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [56]:
data[data[:,0] < 19]

array([[18, 90, 78],
       [17, 81, 95],
       [18, 70, 70]])

In [58]:
np.mean(data[:,1:],axis=0)

array([86.6, 83.2])

In [69]:
data[(data[:,1] >=80) &( data[:,2] >=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [68]:
data[:,1] >=80

array([ True,  True,  True, False,  True])

In [73]:
data[:,2] < 75

array([False, False, False,  True, False])

In [75]:
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])