In [1]:
import numpy as np

In [2]:
languages = np.array([
    [85, 78, 90, 88, 92],   # Python
    [80, 75, 70, 72, 74],   # Java
    [78, 82, 85, 80, 83],   # JavaScript
    [60, 65, 68, 70, 72],   # C++
    [55, 58, 60, 62, 64]    # Rust
])

In [4]:
print(languages.shape)
print(languages.ndim)
print(languages.size)


(5, 5)
2
25


In [22]:
n = np.mean(languages,axis=1)
n
    

array([86.6, 74.2, 81.6, 67. , 59.8])

In [23]:
for i in n:
    if i < 70:
        i+=70
        
n

array([86.6, 74.2, 81.6, 67. , 59.8])

In [24]:
languages

array([[85, 78, 90, 88, 92],
       [80, 75, 70, 72, 74],
       [78, 82, 85, 80, 83],
       [60, 65, 68, 70, 72],
       [55, 58, 60, 62, 64]])

In [38]:
languages[languages > 75]


array([85, 78, 90, 88, 92, 80, 78, 82, 85, 80, 83])

In [35]:
result = np.all(languages > 75, axis=1)


In [36]:
result

array([ True, False,  True, False, False])

In [37]:
languages[result]

array([[85, 78, 90, 88, 92],
       [78, 82, 85, 80, 83]])